###
POST http://localhost:3000/usuarios/registro
Content-Type: application/json

{
    

     "email": "andres@test.com",
     "contrasena": "test",
     "nombre":  "testandres",
     "usuario": "testandres",
     "telefono": "1111111",
     "direccion": "test"
    

}

###
GET http://localhost:3000/usuarios/obtenerusuarios

###
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "contrasena": "123456"

}

###
POST http://localhost:3000/usuarios/anadirdirecciones/613e6156b06ae7435c3d92d1
Content-Type: application/json

{
    "direccion": "AvenidaSiempreViva"
}